library:
  source-dirs: src
tests:
  ddd-with-haskell-test:
    source-dirs: test
    main: Spec.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ddd-with-haskell
copyright: 2019 Author name here
maintainer: example@example.com
dependencies:
- text
- base >= 4.7 && < 5
name: ddd-with-haskell
version: 0.1.0.0
extra-source-files:
- README.md
- ChangeLog.md
author: Author name here
github: githubuser/ddd-with-haskell
license: BSD3
executables:
  ddd-with-haskell-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ddd-with-haskell
description: Please see the README on GitHub at <https://github.com/githubuser/ddd-with-haskell#readme>
